---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - ../../../../kubenuc/apps/harbor/manifests/release.yml
patchesStrategicMerge:
  - release.yml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - ../../../../kubenuc/apps/harbor/manifests/redis.yml
patchesStrategicMerge:
  - redis.yml
