---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sso
resources:
  - ../../../kubenuc/apps/sso/manifests
patches:
  - path: release.yml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sso
resources:
  - ../../../kubenuc/apps/sso/manifests/zitadel.yml
patches:
  - path: zitadel.yml
