apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - ./manifests/namespace.yml
  - ./manifests/redis.yml
  - ./manifests/release.yml
  - ./manifests/backup.yml
