apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - awx.yml
  - bitnami.yml
  - cetic.yml
  - crowdsec.yml
  - datawire.yml
  - goauthentik.yml
  - harbor.yml
  - longhorn.yml
  - minio.yml
  - k8s-at-home.yml
  - kubernetes-sigs.yml
  - nextcloud.yml
  - portainer.yml
  - prometheus-community.yml
  - sysdig.yml
  - teleport.yml
  - zabbix-community.yml
  - zalando.yml
