---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: awx-chart
  namespace: flux-system
spec:
  interval: 1h
  url: https://ansible-community.github.io/awx-operator-helm/
  timeout: 3m
