apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bareos/deploy-app.yaml
  - cloudflare/deploy.yml
  - coredns/deploy.yaml
  - emissary-ingress/deploy.yaml
  - film-tv-exporter/deploy.yaml
  - fluxcd/notifications.yaml
  - fluxcd/secrets.yaml
  - harbor/deploy.yaml
  - jellyfin/deploy.yaml
  - jenkins/deploy.yaml
  - jfrog-acr/deploy.yaml
  - longhorn/deploy.yaml
  - net-mon/deploy.yaml
  - nextcloud/deploy.yaml
  - nfs-sc/deploy.yaml
  - nut/deploy.yaml
  - openebs/deploy.yaml
  - portainer/deploy.yaml
  - s3/deploy.yaml
  - sso/deploy.yaml
  - sysdig-agent/deploy.yaml
  - sysdig-harbor-scanner/deploy.yaml
  - zabbix/deploy.yaml
  # Excluded (in gitrepository ignore list):
  # - nginx-ingress/deploy.yaml
  # - postgresql/deploy.yaml
  # - system-upgrade-controller/deploy.yaml
  # - unifi/deploy.yaml
