apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1password/deploy.yaml
  - harbor/deploy.yaml
  - jenkins/deploy.yaml
  - nextcloud/deploy.yaml
  - nginx-ingress/deploy.yaml
  - openebs/deploy.yaml
  - portainer/deploy.yaml
  - s3/deploy.yaml
  - sso/deploy.yaml
  - zabbix/deploy.yaml
  - postgresql/deploy.yaml
