---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud-fastnetserv
resources:
  - ../../../../kubenuc/apps/nextcloud/manifests/release.yml
patchesStrategicMerge:
  - release.yml
