---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  interval: 1h
  url: https://haproxytech.github.io/helm-charts
  timeout: 3m
