apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud-fastnetserv
resources:
- nextcloud-db-s3-backup.yml
- nextcloud-db-secret.yml
- nextcloud-mariadb-secret.yml
- nextcloud-secret.yml
